### PR TITLE
fix #179

### LINKED ISSUE #179: RangeError when parsing.
The following code, causes dscanner/libdparse to crash:

```
struct id { this() { foreach( a;1..2) { switch (id) goto
```

The crash gives the following stackrace:
```
core.exception.RangeError@../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d(7193): Range violation
----------------
??:? _d_arrayboundsp [0xc6eeb2]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:7193 const(pure nothrow @property @nogc @safe std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure function()) dparse.parser.Parser.current [0xc41806]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:3088 dparse.ast.GotoStatement dparse.parser.Parser.parseGotoStatement() [0xc3480a]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4843 dparse.ast.StatementNoCaseNoDefault dparse.parser.Parser.parseStatementNoCaseNoDefault() [0xc39f3f]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4768 dparse.ast.Statement dparse.parser.Parser.parseStatement() [0xc39b82]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:5219 dparse.ast.SwitchStatement dparse.parser.Parser.parseSwitchStatement() [0xc3b2ce]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4831 dparse.ast.StatementNoCaseNoDefault dparse.parser.Parser.parseStatementNoCaseNoDefault() [0xc39e87]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4768 dparse.ast.Statement dparse.parser.Parser.parseStatement() [0xc39b82]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2196 dparse.ast.DeclarationOrStatement dparse.parser.Parser.parseDeclarationOrStatement() [0xc3137a]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2165 dparse.ast.DeclarationsAndStatements dparse.parser.Parser.parseDeclarationsAndStatements(bool) [0xc311dc]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:1159 dparse.ast.BlockStatement dparse.parser.Parser.parseBlockStatement() [0xc2d94e]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4811 dparse.ast.StatementNoCaseNoDefault dparse.parser.Parser.parseStatementNoCaseNoDefault() [0xc39d73]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4768 dparse.ast.Statement dparse.parser.Parser.parseStatement() [0xc39b82]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2196 dparse.ast.DeclarationOrStatement dparse.parser.Parser.parseDeclarationOrStatement() [0xc3137a]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2769 dparse.ast.ForeachStatement dparse.parser.Parser.parseForeachStatement() [0xc33531]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4827 dparse.ast.StatementNoCaseNoDefault dparse.parser.Parser.parseStatementNoCaseNoDefault() [0xc39e59]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:4768 dparse.ast.Statement dparse.parser.Parser.parseStatement() [0xc39b82]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2196 dparse.ast.DeclarationOrStatement dparse.parser.Parser.parseDeclarationOrStatement() [0xc3137a]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2165 dparse.ast.DeclarationsAndStatements dparse.parser.Parser.parseDeclarationsAndStatements(bool) [0xc311dc]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:1159 dparse.ast.BlockStatement dparse.parser.Parser.parseBlockStatement() [0xc2d94e]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2874 dparse.ast.FunctionBody dparse.parser.Parser.parseFunctionBody() [0xc33a41]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:1716 dparse.ast.Constructor dparse.parser.Parser.parseConstructor() [0xc2f4c9]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:1967 dparse.ast.Declaration dparse.parser.Parser.parseDeclaration(bool, bool) [0xc30163]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:5078 dparse.ast.StructBody dparse.parser.Parser.parseStructBody() [0xc3aaba]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:5117 dparse.ast.StructDeclaration dparse.parser.Parser.parseStructDeclaration() [0xc3ad7f]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:2079 dparse.ast.Declaration dparse.parser.Parser.parseDeclaration(bool, bool) [0xc30988]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:3918 dparse.ast.Module dparse.parser.Parser.parseModule() [0xc3736e]
../.dub/packages/libdparse-0.7.1-beta.5/libdparse/src/dparse/parser.d:34 dparse.ast.Module dparse.parser.parseModule(const(std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure)[], immutable(char)[], dparse.rollback_allocator.RollbackAllocator*, void function(immutable(char)[], ulong, ulong, immutable(char)[], bool)*, uint*, uint*) [0xc2a32c]
src/main.d:286 _Dmain [0xb5301f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0xc70ccf]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xc70bff]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xc70c78]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xc70bff]
??:? _d_run_main [0xc70b6f]
??:? main [0xb5f7ad]
??:? __libc_start_main [0x7e4e082f]

```

### PR DESCRIPTION
**Pull request by BBasile**
as usual add a tag PLZ, so that the high end JSON descriptions products can be updated.

### CODE REVIEW

**Comment by BBasile** [comment]
ignore appveyor failure (b/c of LDC).

**Comment by wilzbach** [comment]
Simply add a commit that comments ldc-beta out?

**Comment by BBasile** [comment]
done

**Comment by BBasile** [comment]
I need someone to push the `v0.7.2-alpha.5` tag please. I wish to update DCD, D-Scanner and D-Symbol.

**Comment by wilzbach** [comment]
Don't you have the rights yourself?

**Comment by BBasile** [comment]
No. I've left since 2 or 3 months already. But i have to fix the this issue, a simple bound violation, reported and standing for 1 month, it was too much.

**Pull request merged**
