### PR TITLE
fix a few links in the auto gen grammar

### PR DESCRIPTION
**Pull request by BBasile**
all matchs of `RULE\ [A-Z]`

### CODE REVIEW

**Comment by BBasile** [comment]
Is there a preview BTW ?

**Comment by BBasile** [comment]
because see http://libdparse.dlang.io/grammar.html#atAttribute, i still see `TemplateInstance` instead of `templateInstance`

**Comment by wilzbach** [comment]
Nope, sorry.
You can run it locally though: `./DGrammar/generate_html_from_libdparse.sh`

**Comment by wilzbach** [comment]
Ah it takes a few minutes for Travis to run the job and then another few for GH Pages to build and invalidate the cache.

**Comment by BBasile** [comment]
ah okay then, no problem

**Comment by wilzbach** [comment]
You can check here:

**Comment by BBasile** [comment]
@wilzbach, it's still the old version: see `TemplateInstance` in this RULEDEF: http://libdparse.dlang.io/grammar.html#atAttribute. 3 hours already.

**Comment by BBasile** [comment]
it was supposed to be fixed by this PR 😢

**Comment by wilzbach** [comment]
Hmm weird, the `gh-pages` get correctly updated: https://github.com/dlang-community/libdparse/tree/gh-pages by Travis, but I don't know why the GH Pages aren't refreshed :/
I will try to do it manually as an attempt

**Pull request merged**
