### PR TITLE
More DDOC fixes for the grammar, close #205

### LINKED ISSUE #205: DDOC for Grammar - a few problems
see http://libdparse.dlang.io/grammar.html#attributeDeclaration

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
I've carefully checked the result locally and it's good now, i won't update this PR, it can be merged.

**Comment by wilzbach** [comment]
Thanks

**Comment by wilzbach** [comment]
Let's see if this GitHub pages deploy works this time. Otherwise, I guess we have to use rawgit, trigger a build manually or find another solution.

**Comment by BBasile** [comment]
I don't know how this works. While i 100% agree that this was a useful initiative and a good idea, all this CI things are clearly not my cup of tea.

**Pull request merged**
