### PR TITLE
Fix #158 - handle indexer in type identifier chain

### LINKED ISSUE #158: Parsing type expressions involving array indexing is broken
T[1].X y;

Parses/formats back into: ".X y"

The Type/Type2+TypeSuffixes  seems to assume that if it parsed "[1]" it must mean array-of-1, and then mis-handles the ".X" which follows.

There's a fundamental ambiguity here between ordinary expressions yielding types, and type-exprs involving array decls - that is not quite handled correctly by libdparse.

### PR DESCRIPTION
**Pull request by BBasile**
This PR fix the bug, that is a type can be specified using an AliasSeq or a tuple, however it breaks the tools that rely on dparse.

### CODE REVIEW

**Comment by BBasile** [comment]
By the way, dont merge this if you don't want to fix the tools. It's not an easy task.

**Comment by BBasile** [comment]
he he that's the shit right ;)

**Comment by stefan-koch-sociomantic** [comment]
It's fine to add a new Symbol; but please don't remove the existing one.

**Comment by BBasile** [comment]
The problem is that it's wrongly named. I've opened an issue from the D side as well: https://issues.dlang.org/show_bug.cgi?id=17700

**Comment by BBasile** [comment]
Since nobody seems motivated enough to handle this (because of the required changes in dsymbol i suppose) maybe in a first time the construct could be handled but ignored, meaning that `T[0].Y` would parse but will still be handled as `T.Y`.

**Comment by BBasile** [comment]
@Hackerpilot:

I managed to update DSymbol for this change and was able to compile DCD. So i think that the PR can be merged. Two notes:

- as @stefan-koch-sociomantic noted this is a breaking change. There's no way not to break things.
- about DSymbol: in a first time the indexed components will be ignored but i hope to handle tuples and Alisaseq in a near future.

**Comment by BBasile** [comment]
You can see that the conversion was actually very simple:

https://github.com/BBasile/dsymbol/commit/286ae579eaece00f9f7705119f9e05014ed0a9ae

**Comment by BBasile** [comment]
> It's fine to add a new Symbol; but please don't remove the existing one.

Oh you didn't speak about the chain VS list thing. Actually yes i'll put deprecated aliases to simplify the transition.

**Comment by Hackerpilot** [comment]
@stefan-koch-sociomantic How badly is this going to break things for you?

**Comment by BBasile** [comment]
A trick to minimize the impact of the breaking changes would be to put a _0.8.0-alpha.1_ tag after this change (instead of _0.7.2-alpha.7_). DUB will continue using the 0.7.X releases, unless _~> 0.8.0-alpha.1_ is set explicitly in the description.

When used as a submodule the problem does not exists. People can just checkout the last SHA that's good for them.

**Comment by Hackerpilot** [comment]
Yes. This is certainly the kind of change that requires a 0.7 to 0.8 version increment.

**Comment by BBasile** [comment]
Warning, do not merge for now. I'm rewritting. What i named chain is an array of node.

**Comment by BBasile** [comment]
I have to close that and reopen another PR. I had commit directly in the origin.

**Pull request closed without merging**
