### PR TITLE
clone stdx-alloc if not already done for the dlang project tester

### PR DESCRIPTION
**Pull request by BBasile**
xref: https://github.com/dlang/ci/issues/193

### CODE REVIEW

**Comment by BBasile** [comment]
Tag needed if you wish to reactivate dparse at dlang.

**Comment by wilzbach** [comment]
Thanks! Completely lost track of this

**Comment by wilzbach** [comment]
Pushed v0.8.2

**Comment by wilzbach** [comment]
https://github.com/dlang/ci/pull/205

**Pull request merged**
