### PR TITLE
make libdparse compatible with dmd v2.070.2

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
This pr is need for dfmt to be integrated with dmd version sociomantic is using.

### CODE REVIEW

**Comment by wilzbach** [comment]
Why do you need to support such old D versions? What's wrong with using a modern DMD to build dfmt?

**Comment by wilzbach** [comment]
(that's why it's often helpful to use the PR description text)

**Comment by leandro-lucarella-sociomantic** [comment]
I'm almost sure this wasn't really necessary, sorry for the misunderstanding. Please ping me to confirm we really need hacks like these, because normally we shouldn't.

**Comment by wilzbach** [comment]
> I'm almost sure this wasn't really necessary, sorry for the misunderstanding. Please ping me to confirm we really need hacks like these, because normally we shouldn't.

Oh I asked Stefan on Slack and he told me there is no easy way for you guys to use a more modern compiler.
Well, if you don't need this, I think we should revert it...

@stefan-koch-sociomantic ?

**Pull request merged**
