### PR TITLE
lexer: avoid unnecessary allocations on compile-time arrays

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by ljmf00** [comment]
There is no CI?

**Comment by rikkimax** [comment]
> There is no CI?

Doesn't look like it, hasn't been swapped over from Travis to GH actions.

**Comment by WebFreak001** [comment]
seems to fail with GDC

**Comment by ljmf00** [comment]
> seems to fail with GDC

I think this should be accepted by the compiler. I can add `.idup` tho, but seems a compiler bug? CC @ibuclaw

**Comment by WebFreak001** [comment]
DCD build failure is due to [issues.dlang.org/show_bug.cgi?id=23874](https://issues.dlang.org/show_bug.cgi?id=23874)

**Pull request merged**
