### PR TITLE
Try to fix CI

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by LaurentTreguier** [comment]
With `pyenv global system` it should be able to pick up the system-installed python (from https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global)

**Comment by BBasile** [comment]
Yeah but that didn't work. I don't remember in which commit i tried this. :laughing:

**Comment by LaurentTreguier** [comment]
Hmm... Since it's complaining about pip3 not being installed, wouldn't it be fixed by adding `python3-pip` to the apt packages installed ?

**Comment by BBasile** [comment]
pyenv doesn't recognize the version of python 3 that's setup by default (3.4.3). This must be a regression at TravisCI or pyenv. The CI passed when i setup manually another  python version.

**Comment by BBasile** [comment]
I'll try because installing python is slow.

**Comment by BBasile** [comment]
Better wait they fix their regression because this is a silly workaround :clown_face:

**Pull request merged**
